version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: America/Denver
  open-pull-requests-limit: 10
  assignees:
  - blerg-rush
  ignore:
  - dependency-name: rubocop
    versions:
    - ">= 0.72.0.a, < 0.72.1"
  - dependency-name: rubocop
    versions:
    - ">= 0.73.0.a, < 0.73.1"
  - dependency-name: rubocop
    versions:
    - ">= 0.74.a, < 0.75"
  - dependency-name: sorbet-runtime
    versions:
    - 0.5.6287
    - 0.5.6338
    - 0.5.6382
    - 0.5.6391
  - dependency-name: sorbet
    versions:
    - 0.5.6330
    - 0.5.6351
    - 0.5.6388
