version: 1
update_configs:
  - package_manager: "ruby:bundler"
    directory: "/"
    default_assignees:
    - "thewillgabriel"
    update_schedule: "live"
    automerged_updates:
    - match: {dependency_type: "all", update_type: "all"}
