name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: dokku-github-action
        uses: vitalyliber/dokku-github-action@v3.0
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
          HOST: yegrb.com
          PROJECT: yegrb
          FORCE_DEPLOY: true
